services:

  mysql:
    container_name: driving_analysis_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: driving_analysis_redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  driving-analysis-service:
    container_name: driving_analysis_service
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_OUTPUT: ${S3_OUTPUT}
      DRIVING_STREAM_NAME: ${DRIVING_STREAM_NAME}
      DRIVING_CONSUMER_GROUP: ${DRIVING_CONSUMER_GROUP}
      DRIVING_CONSUMER_NAME: ${DRIVING_CONSUMER_NAME}
      REPORT_STREAM_NAME: ${REPORT_STREAM_NAME}
      REPORT_CONSUMER_GROUP: ${REPORT_CONSUMER_GROUP}
      REPORT_CONSUMER_NAME: ${REPORT_CONSUMER_NAME}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql_data:
  redis_data: